# Generated by Django 5.2 on 2025-05-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModelo',
            fields=[
                ('rut', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_visita', models.DateTimeField(blank=True, null=True, verbose_name='Última Visita')),
                ('estado', models.CharField(default='activo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes/Ingredientes/', verbose_name='Imagen')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('nivel_critico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nivel Crítico')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'ingrediente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioModelo',
            fields=[
                ('rut', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='RUT')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_sesion', models.DateTimeField(blank=True, null=True, verbose_name='Última Sesión')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
