# Generated by Django 5.2 on 2025-05-26 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Infraestructura", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredienteModelo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cantidad"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=50, verbose_name="Categoría"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ingredientes/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(max_length=20, verbose_name="Unidad de Medida"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        default="activo", max_length=20, verbose_name="Estado"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "nivel_critico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Nivel Crítico",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Tipo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
                "db_table": "ingrediente",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioModelo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Contraseña encriptada",
                        max_length=128,
                        verbose_name="Password",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "rol",
                    models.CharField(max_length=100, null=True, verbose_name="Rol"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "ultima_sesion",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ultima Sesión"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["-ultima_sesion"],
            },
        ),
        migrations.AlterField(
            model_name="clientemodelo",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, unique=True, verbose_name="Id"
            ),
        ),
    ]
