# Generated by Django 5.2 on 2025-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infraestructura', '0001_initial'),
    ]

    operations = [
        # Eliminar la tabla usuarios si existe
        migrations.RunSQL(
            "DROP TABLE IF EXISTS usuarios CASCADE;",
            reverse_sql="SELECT 1;"
        ),
        # Recrear la tabla usuarios con la estructura correcta
        migrations.CreateModel(
            name='UsuarioModelo',
            fields=[
                ('rut', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='RUT')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_sesion', models.DateTimeField(blank=True, null=True, verbose_name='Última Sesión')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
