# Generated by Django 5.2.1 on 2025-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Infraestructura", "0002_ingredientemodelo_usuariomodelo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientemodelo",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Imagenes/Ingredientes/",
                verbose_name="Imagen",
            ),
        ),
    ]
