# Generated by Django 5.2 on 2025-05-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infraestructura', '0002_auto_20250529_0858'),
    ]

    operations = [
    ]
