# Generated by Django 4.2.16 on 2025-07-25 08:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Infraestructura", "0003_auto_20250529_0900"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAppModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("comision", models.DecimalField(decimal_places=2, max_digits=5)),
                ("api_endpoint", models.URLField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("activa", models.BooleanField(default=True)),
                ("configuracion_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Aplicación de Delivery",
                "verbose_name_plural": "Aplicaciones de Delivery",
                "db_table": "delivery_app",
            },
        ),
        migrations.CreateModel(
            name="MedioPagoModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("transferencia", "Transferencia Bancaria"),
                            ("app_pago", "Aplicación de Pago"),
                            ("crypto", "Criptomoneda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("requiere_validacion", models.BooleanField(default=False)),
                ("configuracion_api", models.JSONField(blank=True, default=dict)),
                (
                    "comision_porcentaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Medio de Pago",
                "verbose_name_plural": "Medios de Pago",
                "db_table": "medio_pago",
            },
        ),
        migrations.CreateModel(
            name="MesaModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Identificador único de la mesa",
                        max_length=10,
                        unique=True,
                        verbose_name="Número de Mesa",
                    ),
                ),
                (
                    "capacidad",
                    models.PositiveIntegerField(
                        help_text="Cantidad máxima de personas que pueden sentarse",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Capacidad",
                    ),
                ),
                (
                    "tipo_mesa",
                    models.CharField(
                        choices=[
                            ("individual", "Individual (1-2 personas)"),
                            ("pequeña", "Pequeña (3-4 personas)"),
                            ("mediana", "Mediana (5-6 personas)"),
                            ("grande", "Grande (7-8 personas)"),
                            ("familiar", "Familiar (9+ personas)"),
                            ("vip", "VIP"),
                        ],
                        default="pequeña",
                        help_text="Clasificación de la mesa según su capacidad",
                        max_length=20,
                        verbose_name="Tipo de Mesa",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Zona del restaurante donde está ubicada la mesa",
                        max_length=100,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "caracteristicas",
                    models.TextField(
                        blank=True,
                        help_text="Características especiales de la mesa (vista, accesibilidad, etc.)",
                        verbose_name="Características",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("ocupada", "Ocupada"),
                            ("reservada", "Reservada"),
                            ("limpieza", "En Limpieza"),
                            ("fuera_servicio", "Fuera de Servicio"),
                        ],
                        default="libre",
                        help_text="Estado actual de la mesa",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la mesa está disponible para servicio",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "cantidad_personas_actual",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cantidad de personas actualmente en la mesa",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Personas Actuales",
                    ),
                ),
                (
                    "pedido_id_actual",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID del pedido asociado a la mesa actual",
                        null=True,
                        verbose_name="Pedido Actual",
                    ),
                ),
                (
                    "hora_ocupacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que la mesa fue ocupada",
                        null=True,
                        verbose_name="Hora de Ocupación",
                    ),
                ),
                (
                    "hora_liberacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que la mesa fue liberada",
                        null=True,
                        verbose_name="Hora de Liberación",
                    ),
                ),
                (
                    "tiempo_servicio_promedio",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tiempo promedio de servicio en minutos",
                        null=True,
                        verbose_name="Tiempo Promedio de Servicio",
                    ),
                ),
                (
                    "total_servicios",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número total de veces que la mesa ha sido ocupada",
                        verbose_name="Total de Servicios",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "cliente_actual",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente que actualmente ocupa la mesa",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mesa_ocupada",
                        to="Infraestructura.clientemodelo",
                        verbose_name="Cliente Actual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesa",
                "verbose_name_plural": "Mesas",
                "db_table": "mesas",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="PedidoModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pedido",
                    models.CharField(
                        choices=[
                            ("mesa", "Mesa"),
                            ("delivery", "Delivery"),
                            ("para_llevar", "Para Llevar"),
                        ],
                        default="mesa",
                        help_text="Tipo de pedido",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmado", "Confirmado"),
                            ("en_preparacion", "En Preparación"),
                            ("listo", "Listo"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        help_text="Estado actual del pedido",
                        max_length=20,
                    ),
                ),
                (
                    "direccion_entrega",
                    models.TextField(
                        blank=True,
                        help_text="Dirección de entrega (solo para delivery)",
                        null=True,
                    ),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "observaciones_generales",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones generales del pedido",
                        null=True,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación del pedido",
                    ),
                ),
                (
                    "fecha_confirmacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de confirmación del pedido",
                        null=True,
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de entrega del pedido",
                        null=True,
                    ),
                ),
                (
                    "tiempo_preparacion_estimado",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tiempo estimado de preparación en minutos",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(480),
                        ],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total del pedido",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente que realizó el pedido",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="Infraestructura.clientemodelo",
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mesa asignada (solo para pedidos de mesa)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="Infraestructura.mesamodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": "pedidos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryPedidoModelo",
            fields=[
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="delivery",
                        serialize=False,
                        to="Infraestructura.pedidomodelo",
                        verbose_name="Pedido Base",
                    ),
                ),
                (
                    "direccion_entrega",
                    models.CharField(
                        max_length=255, verbose_name="Dirección de Entrega"
                    ),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono de Contacto"
                    ),
                ),
                (
                    "aplicacion_externa",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Aplicación Externa",
                    ),
                ),
                (
                    "costo_envio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo de Envío",
                    ),
                ),
                (
                    "repartidor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Repartidor"
                    ),
                ),
                (
                    "codigo_seguimiento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Código de Seguimiento",
                    ),
                ),
                (
                    "hora_salida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Salida"
                    ),
                ),
                (
                    "tiempo_estimado_entrega",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tiempo Estimado de Entrega (min)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido Delivery",
                "verbose_name_plural": "Pedidos Delivery",
                "db_table": "delivery_pedido",
            },
        ),
        migrations.CreateModel(
            name="TransaccionModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monto_comision",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("exitosa", "Exitosa"),
                            ("fallida", "Fallida"),
                            ("cancelada", "Cancelada"),
                            ("reembolsada", "Reembolsada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("codigo_referencia", models.CharField(max_length=100, unique=True)),
                ("datos_adicionales", models.JSONField(blank=True, default=dict)),
                ("fecha_transaccion", models.DateTimeField(auto_now_add=True)),
                ("fecha_procesamiento", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "medio_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transacciones",
                        to="Infraestructura.mediopagomodelo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="Infraestructura.pedidomodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "db_table": "transaccion",
                "ordering": ["-fecha_transaccion"],
            },
        ),
        migrations.CreateModel(
            name="MenuModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del menú",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del menú",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del menú en pesos chilenos",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        help_text="Categoría del menú (ej: entrada, plato principal, postre)",
                        max_length=100,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        help_text="Tipo específico del menú (ej: vegetariano, vegano, sin gluten)",
                        max_length=100,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el menú está disponible para ordenar",
                        verbose_name="Disponible",
                    ),
                ),
                (
                    "imagen",
                    models.URLField(
                        blank=True,
                        help_text="URL de la imagen del menú",
                        null=True,
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Última Actualización"
                    ),
                ),
                (
                    "veces_ordenado",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de veces que se ha ordenado este menú",
                        verbose_name="Veces Ordenado",
                    ),
                ),
                (
                    "tiempo_preparacion",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Tiempo estimado de preparación en minutos",
                        verbose_name="Tiempo de Preparación",
                    ),
                ),
                (
                    "ingredientes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ingredientes necesarios para preparar este menú",
                        to="Infraestructura.ingredientemodelo",
                        verbose_name="Ingredientes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menú",
                "verbose_name_plural": "Menús",
                "db_table": "menu",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedidoModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        help_text="Cantidad solicitada del item",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio unitario al momento del pedido",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones específicas para este item",
                        null=True,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal del item (cantidad × precio_unitario)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="Item del menú solicitado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_pedido",
                        to="Infraestructura.menumodelo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        help_text="Pedido al que pertenece este item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Infraestructura.pedidomodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pedido",
                "verbose_name_plural": "Items de Pedido",
                "db_table": "items_pedido",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryRepartidorModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_ruta", "En Ruta"),
                            ("ocupado", "Ocupado"),
                            ("desconectado", "Desconectado"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("vehiculo", models.CharField(blank=True, max_length=50)),
                (
                    "ubicacion_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "ubicacion_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repartidores",
                        to="Infraestructura.deliveryappmodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repartidor de Delivery",
                "verbose_name_plural": "Repartidores de Delivery",
                "db_table": "delivery_repartidor",
            },
        ),
        migrations.AddIndex(
            model_name="pedidomodelo",
            index=models.Index(fields=["estado"], name="pedidos_estado_b14829_idx"),
        ),
        migrations.AddIndex(
            model_name="pedidomodelo",
            index=models.Index(
                fields=["tipo_pedido"], name="pedidos_tipo_pe_a60644_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedidomodelo",
            index=models.Index(
                fields=["fecha_creacion"], name="pedidos_fecha_c_3cb5bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedidomodelo",
            index=models.Index(fields=["cliente"], name="pedidos_cliente_e28e20_idx"),
        ),
        migrations.AddIndex(
            model_name="pedidomodelo",
            index=models.Index(fields=["mesa"], name="pedidos_mesa_id_477d4f_idx"),
        ),
        migrations.AddConstraint(
            model_name="pedidomodelo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("tipo_pedido", "mesa"), ("mesa__isnull", True), _negated=True
                ),
                name="pedido_mesa_requiere_mesa",
            ),
        ),
        migrations.AddConstraint(
            model_name="pedidomodelo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("tipo_pedido", "delivery"),
                    ("direccion_entrega__isnull", True),
                    _negated=True,
                ),
                name="pedido_delivery_requiere_direccion",
            ),
        ),
        migrations.AddConstraint(
            model_name="pedidomodelo",
            constraint=models.CheckConstraint(
                check=models.Q(("total__gte", 0)), name="pedido_total_positivo"
            ),
        ),
        migrations.AddIndex(
            model_name="mesamodelo",
            index=models.Index(fields=["numero"], name="mesas_numero_d5b446_idx"),
        ),
        migrations.AddIndex(
            model_name="mesamodelo",
            index=models.Index(fields=["estado"], name="mesas_estado_d31b82_idx"),
        ),
        migrations.AddIndex(
            model_name="mesamodelo",
            index=models.Index(fields=["capacidad"], name="mesas_capacid_503550_idx"),
        ),
        migrations.AddIndex(
            model_name="mesamodelo",
            index=models.Index(fields=["tipo_mesa"], name="mesas_tipo_me_12a794_idx"),
        ),
        migrations.AddIndex(
            model_name="mesamodelo",
            index=models.Index(fields=["activa"], name="mesas_activa_c70c3a_idx"),
        ),
        migrations.AddIndex(
            model_name="menumodelo",
            index=models.Index(fields=["categoria"], name="menu_categor_81634c_idx"),
        ),
        migrations.AddIndex(
            model_name="menumodelo",
            index=models.Index(fields=["disponible"], name="menu_disponi_162b87_idx"),
        ),
        migrations.AddIndex(
            model_name="menumodelo",
            index=models.Index(fields=["precio"], name="menu_precio_ea0db3_idx"),
        ),
        migrations.AddIndex(
            model_name="menumodelo",
            index=models.Index(
                fields=["-veces_ordenado"], name="menu_veces_o_7ff28d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="menumodelo",
            constraint=models.CheckConstraint(
                check=models.Q(("precio__gt", 0)), name="precio_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="menumodelo",
            constraint=models.CheckConstraint(
                check=models.Q(("tiempo_preparacion__gt", 0)),
                name="tiempo_preparacion_positivo",
            ),
        ),
        migrations.AddIndex(
            model_name="itempedidomodelo",
            index=models.Index(
                fields=["pedido"], name="items_pedid_pedido__cbe751_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itempedidomodelo",
            index=models.Index(fields=["menu"], name="items_pedid_menu_id_d9218f_idx"),
        ),
        migrations.AddConstraint(
            model_name="itempedidomodelo",
            constraint=models.CheckConstraint(
                check=models.Q(("cantidad__gt", 0)), name="item_cantidad_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedidomodelo",
            constraint=models.CheckConstraint(
                check=models.Q(("precio_unitario__gt", 0)), name="item_precio_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedidomodelo",
            constraint=models.CheckConstraint(
                check=models.Q(("subtotal__gte", 0)), name="item_subtotal_positivo"
            ),
        ),
        migrations.AddField(
            model_name="deliveryrepartidormodelo",
            name="pedido_actual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repartidor_actual",
                to="Infraestructura.deliverypedidomodelo",
            ),
        ),
    ]
